server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: wholeSale
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

product:
  service:
    url: http://productDB
