spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: productDB
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8088

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true