spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bev0802/sales-config
          clone-on-start: true

server:
  port: 8888
